// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5250.robot.subsystems;

import org.usfirst.frc5250.robot.RobotMap;
import org.usfirst.frc5250.robot.commands.*;
import org.usfirst.frc5250.robot.commands.pawl.DriveTrainDefault;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar canJaguar21 = RobotMap.driveTraincanJaguar21;
    CANJaguar canJaguar22 = RobotMap.driveTraincanJaguar22;
    CANJaguar canJaguar23 = RobotMap.driveTraincanJaguar23;
    CANJaguar canJaguar24 = RobotMap.driveTraincanJaguar24;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    AnalogInput analogInput0 = RobotMap.driveTrainanalogInput0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveTrainDefault());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

