// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5250.robot;

import org.usfirst.frc5250.robot.commands.*;
import org.usfirst.frc5250.robot.commands.pawl.DriveTrainDefault;
import org.usfirst.frc5250.robot.commands.pawl.PawlClose;
import org.usfirst.frc5250.robot.commands.pawl.PawlCloseLeft;
import org.usfirst.frc5250.robot.commands.pawl.PawlCloseRight;
import org.usfirst.frc5250.robot.commands.pawl.PawlOpen;
import org.usfirst.frc5250.robot.commands.pawl.PawlOpenLeft;
import org.usfirst.frc5250.robot.commands.pawl.PawlOpenRight;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton button5;
    public JoystickButton button6;
    public Joystick joystick0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick0 = new Joystick(0);
        
        button6 = new JoystickButton(joystick0, 6);
        button6.whileHeld(new PawlClose());
        button5 = new JoystickButton(joystick0, 5);
        button5.whileHeld(new PawlOpen());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("AutonomousCommand", new AutonomousCommand());

        SmartDashboard.putData("CommandBase", new CommandBase());

        SmartDashboard.putData("DriveTrainDefault", new DriveTrainDefault());

        SmartDashboard.putData("PawlClose", new PawlClose());

        SmartDashboard.putData("PawlCloseLeft", new PawlCloseLeft());

        SmartDashboard.putData("PawlCloseRight", new PawlCloseRight());

        SmartDashboard.putData("PawlOpen", new PawlOpen());

        SmartDashboard.putData("PawlOpenLeft", new PawlOpenLeft());

        SmartDashboard.putData("PawlOpenRight", new PawlOpenRight());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick0() {
        return joystick0;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

