// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5250.robot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar driveTraincanJaguar21;
    public static CANJaguar driveTraincanJaguar22;
    public static CANJaguar driveTraincanJaguar23;
    public static CANJaguar driveTraincanJaguar24;
    public static RobotDrive driveTrainRobotDrive;
    public static AnalogInput driveTrainanalogInput0;
    public static SpeedController pawlLefttalon0;
    public static DigitalInput pawlLeftdigitalInput0;
    public static DigitalInput pawlLeftdigitalInput1;
    public static SpeedController pawlRighttalon1;
    public static DigitalInput pawlRightdigitalInput2;
    public static DigitalInput pawlRightdigitalInput3;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTraincanJaguar21 = new CANJaguar(11);
        
        
        driveTraincanJaguar22 = new CANJaguar(12);
        
        
        driveTraincanJaguar23 = new CANJaguar(13);
        
        
        driveTraincanJaguar24 = new CANJaguar(14);
        
        
        driveTrainRobotDrive = new RobotDrive(driveTraincanJaguar21, driveTraincanJaguar22,
              driveTraincanJaguar23, driveTraincanJaguar24);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        driveTrainanalogInput0 = new AnalogInput(0);
        LiveWindow.addSensor("DriveTrain", "analogInput0", driveTrainanalogInput0);
        
        pawlLefttalon0 = new Talon(0);
        LiveWindow.addActuator("PawlLeft", "talon0", (Talon) pawlLefttalon0);
        
        pawlLeftdigitalInput0 = new DigitalInput(0);
        LiveWindow.addSensor("PawlLeft", "digitalInput0", pawlLeftdigitalInput0);
        
        pawlLeftdigitalInput1 = new DigitalInput(1);
        LiveWindow.addSensor("PawlLeft", "digitalInput1", pawlLeftdigitalInput1);
        
        pawlRighttalon1 = new Talon(1);
        LiveWindow.addActuator("PawlRight", "talon1", (Talon) pawlRighttalon1);
        
        pawlRightdigitalInput2 = new DigitalInput(2);
        LiveWindow.addSensor("PawlRight", "digitalInput2", pawlRightdigitalInput2);
        
        pawlRightdigitalInput3 = new DigitalInput(3);
        LiveWindow.addSensor("PawlRight", "digitalInput3", pawlRightdigitalInput3);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
